Milestone 1 : First Pull Request for my second project - Microverse Portfolio
duaneandrea/microverse-portfolio pull request #1
Opened 2023-06-07 15:03 UTC by duaneandrea

- Managed to setup the linter configurations
- Managed to download all the images in SVG format from Figma
- Managed to add style.css file and index.html file to create the webpage copying the css rules and modifying them from  Figma
- Managed to create License file and Readme file

2023-06-07 16:09 UTC, roshan-bajgain requested changes
Hi @duaneandrea, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
- No linter errors. ✔️
- GitHub flow is followed. ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-07 16:09 UTC, roshan-bajgain commented on index.html
> +
- [ ] I would suggest you please use the `h2-h6` tag for subheading This way will be semantically correct.

2023-06-07 16:09 UTC, roshan-bajgain commented on index.html
> +            </h2>
- [ ] According to the project requirement you should stick to the design as much as possible like color, font, spacing.
- [ ] I would suggest please increase the font weight of main heading and also use the same color for logo and same font-weight.
### Your design
![his](https://github.com/duaneandrea/microverse-portfolio/assets/81727988/8fcbf2ca-4762-44e2-92de-5375f5cc4db2)

### Figma design
![fimga](https://github.com/duaneandrea/microverse-portfolio/assets/81727988/b13827b8-cccb-4337-9c16-f3a5dfdb171c)

2023-06-07 16:09 UTC, roshan-bajgain commented on index.html
> +    </section>
- [ ] [Optional]You can remove this for now as you will be doing in further project

2023-06-07 16:23 UTC, duaneandrea commented on index.html
> +            </nav>
@roshan-bajgain im not understanding this point.

2023-06-07 16:23 UTC, duaneandrea commented on index.html
> +            </h2>
@roshan-bajgain done!!

2023-06-07 16:38 UTC, roshan-bajgain commented on index.html
> +            </nav>
Hello @duaneandrea, I am suggesting you that please use the `nav` tag for the hamburger button only as you wrap both logo and hamburger buttons. Just wrap hamburger buttons only. I am sorry I cannot make you clear. Hope you get it.

2023-06-07 16:41 UTC, duaneandrea commented on index.html
> +            </nav>
Okay thank you I have understood and i have finished

2023-06-07 17:27 UTC, stanleySimeon requested changes
# Hi @duaneandrea, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
![](https://media2.giphy.com/media/vQGBDTkhtIunaJYmRF/giphy-downsized.gif?cid=29caca75sf3uq9y4qgulk5ybbojwg94b4zo6temfzeel417x&ep=v1_gifs_search&rid=giphy-downsized.gif&ct=g
)

 ## Highlights
- Correct use of Gitflow ✔️
- Linter checks are passed ✔️
- Good PR description ✔️
- Meaningful commit messages ✔️

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-07 17:27 UTC, stanleySimeon commented on index.html
> +            </h2>
Based on the conversation with the previous reviewer, it seems like there was a suggestion to adhere to the project requirements and stick to the design as much as possible, including the color, font, and spacing. The suggestion was to increase the font weight of the main heading and use the same color and font-weight for the logo as well. 
Kindly, I suggest you fix that before asking for another review

> ## The Figma Design
>
><img width="311" alt="Screenshot 2023-06-07 at 1 19 54 PM" src="https://github.com/duaneandrea/microverse-portfolio/assets/91237525/c6d0006b-da90-4c83-ab9a-4d2e2130aab5">
>
> ## Your Design
>
><img width="376" alt="Screenshot 2023-06-07 at 1 14 57 PM" src="https://github.com/duaneandrea/microverse-portfolio/assets/91237525/4848c0d1-c89a-41ba-be35-7afbabce5f66">

2023-06-08 07:11 UTC, duaneandrea commented on index.html
> +            </h2>
@stanleySimeon Im not quite understanding the required correction. Please ellaborate.

2023-06-08 10:36 UTC, LionRouge1 requested changes
Hi @duaneandrea, 

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![almost](https://media.giphy.com/media/R2m2NzVxQ3pbG/giphy.gif)

## Suggested changes :recycle: 

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-06-08 10:36 UTC, LionRouge1 commented on style.css
> +  }
[OPTIONAL]
- [ ] Since we are using mobile first approach it would be nice to not use media queries `@media` for now. To make the page responsive use values in your CSS rules, like percentages (i.e. width: 80%), instead of pixels (please don't use percentages for `font-size`, `font-weight`). You will learn about media queries in the next milestones.

2023-06-08 10:36 UTC, LionRouge1 commented on style.css
> +    margin-top: 10%;
- [ ] Nice work making the changes :clap: However the changes that you made has put some bugs in your project. Kindly remove the `margin-top` of the `.container` to follow the Figma design
### Your design :point_down: 
![Screenshot from 2023-06-08 10-12-41](https://github.com/duaneandrea/microverse-portfolio/assets/91142432/8c521e1e-b553-4917-af4b-6db3301beae9)
### Figma design :point_down: 
![Screenshot from 2023-04-08 19-44-56](https://github.com/duaneandrea/microverse-portfolio/assets/91142432/bb0d388e-4918-4db9-a398-b65913b0fad7)

2023-06-08 10:36 UTC, LionRouge1 commented on style.css
> +    padding-top: 15%;
[OPTIONAL]
- [ ] It would be nice to add more space at the top of title to follow the figma design.
**HIT: `padding-top: 40%` could fix the problem**
### Your design :point_down: 
![Screenshot from 2023-06-08 10-30-58](https://github.com/duaneandrea/microverse-portfolio/assets/91142432/29d34912-7bd9-4ee5-bdaa-d956b0a76dce)
### Figma design :point_down: 
![Screenshot from 2023-06-08 10-31-43](https://github.com/duaneandrea/microverse-portfolio/assets/91142432/74cf5707-810b-4241-a73f-c34df0de9e1e)

2023-06-08 11:19 UTC, duaneandrea commented on style.css
> +  }
Since it is optional can i leave it like this? @LionRouge1

2023-06-08 12:27 UTC, Gambit142 approved these changes
Hi @duaneandrea 👋,

## Status: Approved 🟢   

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉

### Highlights
- All linters checks passed ✔️ 
- Use of semantic tags ✔️ 
- Adopted colours and fonts from Figma ✔️ 

### Optional Suggestions
- #### Kindly consider the comments tagged _**[OPTIONAL]**_ they will make your design better and responsive. 👍 

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please tag me in your question so I can receive the notification. You can tag me by typing @Gambit142

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-08 12:27 UTC, Gambit142 commented on index.html
> +          <a href="" class="alogo"> My Logo</a>
- [OPTIONAL] Based on the requirements, the header tag should have its children's elements outlined with `flexbox`. Using `flexbox` to align elements makes your design responsive. I would advise you to use this. 😎 

#### Hint:
```CSS
header {
  padding: 1.625rem 1.5rem 0 1.5rem;
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
}
```
#### Then you remove the `padding` property from the logo element with `class="alogo"` and add a `margin-top` property of `-0.4rem` to the `img` tag which contains the hamburger image. 👍 💻

2023-06-08 12:27 UTC, Gambit142 commented on style.css
> +}
- [OPTIONAL] Your design is not responsive across various mobile screen sizes. 🙅 

![chrome-capture-2023-5-8](https://github.com/duaneandrea/microverse-portfolio/assets/77106962/52def843-cc94-4a57-932a-4e0ad6fa5fc2)

#### Hint: To make your design responsive, you need to do the following:

- Remove the width of `375px` from the `div` tag with `class='container'` and add `display: flex;` `flex-direction: column` properties to that same element
- To the `div` tag with `class=headline`, add the following properties:
  - `background-repeat: no-repeat;`
  - `background-size: cover;`
- To the `section` tag with `class=intro` add the following properties:
  - `display: flex;`
  - `flex-direction: column;`

2023-06-08 12:40 UTC, merged