Desktop portfolio milestone
duaneandrea/microverse-portfolio pull request #5
Opened 2023-06-15 14:10 UTC by duaneandrea

- Modified index.html to add new classes
- Modified style.css to add media queries
- Added images in svg format so that they would appear in desktop version

2023-06-15 15:49 UTC, shahadat3669 requested changes
Hi @duaneandrea , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media1.giphy.com/media/m3864rBwwBTKMAbpn3/giphy.gif"/>

## Highlights
✅ Good PR Title
✅ Good PR Description.
✅ Good use of GitHub Flows.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

## Have any doubt ❓

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

## ⚠️ WARNING ⚠️
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-15 15:49 UTC, shahadat3669 commented on index.html
> +          <p class="connect">LET'S CONNECT</p>
Well done on your implementation! I noticed that the text "LET'S CONNECT" is currently wrapped in a `<p>` tag. However, according to the design specifications, it should be considered as a subtitle for your social links.

To align your implementation with the design, I recommend updating the markup to use a more appropriate HTML element for a subtitle, such as a `<h3>` or `<h4>` tag. This will ensure that the structure and semantics of your document are consistent and clear. 🙏 

Please make the necessary adjustment to use an appropriate HTML element for the subtitle.  Keep up the great work! 👍

2023-06-15 15:49 UTC, shahadat3669 commented on index.html
> +    <section class="work">
Well done on the work section cards! 👍 However, there are a few improvements that can be made to align the cards properly and match the font styles with the design:

1. Alignment: Currently, the cards in the work section do not align well as per the design. It is important to ensure that the cards are evenly spaced and aligned to create a visually pleasing layout. Please adjust the spacing and alignment of the cards to match the design specifications.

2. Font styles: The font styles used in the cards do not match the design. It is crucial to maintain consistency in font size, type, and other styles throughout your webpage. Please update the font styles of the cards to align with the design requirements.

| Your | Design |
| --- | --- |
|   ![Group 1](https://github.com/duaneandrea/microverse-portfolio/assets/55840999/b6701296-5a6f-4216-9a64-98c812de7651)   |  ![Group 2 (1)](https://github.com/duaneandrea/microverse-portfolio/assets/55840999/92cce9f1-4d73-487a-b10f-02e7ab4b88f9)     |

By making these adjustments, you will improve the overall visual appeal and consistency of the work section. Keep up the great work! 😄

2023-06-15 15:49 UTC, shahadat3669 commented on index.html
Overall, your design looks good, but there are some elements that are not aligned properly. It's important to ensure that all elements are properly positioned and aligned according to the design specifications.  🙏 

Please refer to the image below and make the necessary adjustments to your code to achieve proper alignment:

| Your | Professional |
| --- | --- |
|  ![Frame 2 (2)](https://github.com/duaneandrea/microverse-portfolio/assets/55840999/8f7a22f0-4aa6-4a0c-b9b3-48352de93ab6)  |  ![Frame 1 (1)](https://github.com/duaneandrea/microverse-portfolio/assets/55840999/3feb165e-4b83-4907-b1af-465e7793a7ae)  |

Take note of the spacing, margins, and positioning of the various elements in the design and apply them to your code. This will help create a more visually pleasing and consistent layout. Keep up the good work! 👍

2023-06-16 13:49 UTC, Zuhaib042 approved these changes
Hi @duaneandrea 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![](https://media.giphy.com/media/3o7abKhOpu0NwenH3O/giphy.gif)
## Highlights
✅ Descriptive PR
✅ Professional Readme
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-16 13:59 UTC, merged